### PR TITLE
Now it Promisify!

### PR DESCRIPTION
**Pull request by ViGo5190**
```
var telegram = require('telegram-bot-api');
var api = new telegram({
    token: '<YOUR TOKEN>'
});

api.getMe()
    .then(function (msg) {
        console.log(msg);
    })
    .catch(function (err) {
        console.log(err);
    });
```

### CODE REVIEW

**Comment by AliMD** [comment]
:ok_hand: 
Thank you
Is it backward compatible ?

**Comment by ViGo5190** [comment]
@AliMD not at all. Some functions, which have callback sintax `function(err, data)` - should work.

**Comment by benjick** [comment]
Bump 

Callbacks are dead

**Comment by mast** [comment]
Implemented in 1.0.0. Thank you @ViGo5190 
I updated it a bit to make it backwards compatible. So old code should also work with new "promisified" API.

**Pull request closed without merging**
