### PR TITLE
Fix an issue in sendChatAction and add new features

### PR DESCRIPTION
**Pull request by mehdi-ghezal**
I found an issue with sendChatAction, sorry for the number of change but I think my editor (Atom) have rewrite some EOL.

### CODE REVIEW

**Comment by AliMD** [comment]
Witch issue ?
Please more describe the bug.

**Comment by mast** [comment]
@AliMD he/she is referring to issue he fixed in https://github.com/mehdi-ghezal/telegram-bot-api/commit/d69f3a0208a58c104a3e9d45861c00a2df751892 
This issue is actually already fixed in latest version of telegram-bot-api.
I don't close this merge request just because there are some remaining new features mehdi proposed in this pull request, which we need to think a bit about.

**Comment by mehdi-ghezal** [comment]
Hi,

I confirm that the issue I talk about has been fixed in last version of telegram-bot-api.
About the features, I implement it for my own need and I share it back with the community.

Mehdi

**Comment by AliMD** [comment]
@mehdi-ghezal please close the issue

مهدی جان مشتاق آشنایی، تو تلگرام با من  تماس بگیر
`@al1md`

**Pull request closed without merging**
