### PR TITLE
Add SendPoll Method

### PR DESCRIPTION
**Pull request by pedroaf0**
Add SendPoll Method to the library
https://core.telegram.org/bots/api#sendpoll

following the update:
April 24, 2020
Bot API 4.8

- Supported explanations for Quizzes 2.0. Add explanations by specifying the parameters explanation and explanation_parse_mode in the method sendPoll.

- Added the fields explanation and explanation_entities to the Poll object.

- Supported timed polls that automatically close at a certain date and time. Set up by specifying the parameter open_period or close_date in the method sendPoll.

- Added the fields open_period and close_date to the Poll object.

### CODE REVIEW

**Comment by mast** [comment]
Why did you remove https support for webhook and caption parameters?

**Comment by pedroaf0** [comment]
@mast sorry for the mess, the last commit should not be here...
is there any way to remove it to leave only the "Add SendPoll method" changes?


about the last commit:

- Express is useless in this context. do you agree?

- https too, I think people will only use the lib on a services like heroku (so the webhook URL will be https anyway) that way, just using http simplifies things a lot

- I just think that the way to add a webhook can be simpler, just being necessary to indicate the URL (already with the port, if necessary) and the parameter 'port' refers to the listening port (because not always the listening will be the same as the url)

**Comment by pedroaf0** [comment]
I will wait for you to answer me before deleting this fork to create a more suitable one. Nothing will be lost 😉

**Comment by mast** [comment]
You can't just delete functionality that could have been used by other people. Somebody is using https and expect it to be there, even if you think it's not needed.
You can just post new pull request. I'm not sure you can remove commits. But you can create new commit which recovers changes and post it to this pull request.

**Pull request closed without merging**
